CREATE TABLE users(
 uid INT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(100) NOT NULL,
 email VARCHAR(100) NOT NULL UNIQUE,
 user_type ENUM('User', 'Engineer', 'Admin') NOT NULL, 
 password VARCHAR(255) NOT NULL
);
